### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by morangeous** [upbit/lldb-capstone-arm#3]
Hello upbit! Thank you so much for developing this plugin for lldb, which helps me a lot.

And recently, I found that there may be something wrong with the parameter parsing code in dis_capstone.py. 
More specifically, this plugin parses the length of byte by this line:
`disasm_length = options.length`

However, this will cause type error, for the type of options.length is str instead of int
Therefore, maybe we can fix it up by the following line:
`disasm_length = int(options.length, 10)`
And also, we should replace 
`parser.add_option('-l', '--length', dest='length', help='decode bytes length (default: 32)', default=32)`
by this line
`parser.add_option('-l', '--length', dest='length', help='decode bytes length (default: 32)', default="32")`

And I really appreciate your contribution to this plugin.

Moran

**Comment by upbit** [comment]
I'm glad this code helped you.

It looks like there's something wrong with the type:
  `parser.add_option('-l', '--length', dest='length', help='decode bytes length (default: 32)', default="32")`

the `length` will be string, and make sure `disasm_length` is int (for capstone):
`disasm_length = int(options.length)`

However, I don't have a test environment at present, so I can't verify whether this modification passes.
If you verify that it works, please feel free to submit a merge request

**Comment by morangeous** [comment]
Nice to get your reply.

I have verified that the change can work in my test environment. But I have modified dis_capstone.py a lot in my project, some of them are confusing for others. 

Hence, when I finish my project, I will submit a merge request in a clean environment.

See you then upbit!
 
Moran
